= Frequently Asked Questions (FAQs)

This page will be updated regularly by CSC8110 demonstrators to include answers to frequently asked questions and solutions to any issues encountered by students.

If you are encountering an issue and cannot find a solution here, please do not hesitate to contact a demonstrator during the practical sessions, or post to the relevant forum on the Blackboard discussion boards.

If there is something you would like to appear on this page, don't hesitate to contact Matthew Forshaw (mailto:matthew.forshaw@ncl.ac.uk[matthew.forshaw@ncl.ac.uk])  and he will update the page accordingly.

'''

== Practical Tutorials

=== I am working on the VM pracical, but I'm based on Windows and find generating an SSH confusing. Is it sufficient for me to use the conventional 'password' approach at this stage?

Authentication using SSH keys is the best-practice way of remotely authenticating with a server, but for the purposes of this tutorial, yes, it would be fine to use a password-based apporach.

== Coursework
None (yet).
