= Frequently Asked Questions (FAQs)

This page will be updated regularly by CSC8110 demonstrators to include answers to frequently asked questions and solutions to any issues encountered by students.

If you are encountering an issue and cannot find a solution here, please do not hesitate to contact a demonstrator during the practical sessions, or post to the relevant forum on the Blackboard discussion boards.

If there is something you would like to appear on this page, don't hesitate to contact Matthew Forshaw (mailto:matthew.forshaw@ncl.ac.uk[matthew.forshaw@ncl.ac.uk])  and he will update the page accordingly.

'''

== Practical Tutorials

=== I am working on the VM pracical, but I'm based on Windows and find generating an SSH confusing. Is it sufficient for me to use the conventional 'password' approach at this stage?

Authentication using SSH keys is the best-practice way of remotely authenticating with a server, but for the purposes of this tutorial, yes, it would be fine to use a password-based apporach.

== Coursework

=== Common Issue: HTTP Error 400. The request has an invalid header name.

If you receive an exception as follows, this may be due to including a space in the name of a property e.g. `message.setProperty("Registration Plate",plate)`. Removing the space will fix the issue.

----
com.microsoft.windowsazure.exception.ServiceException: com.sun.jersey.api.client.UniformInterfaceException: POST https://nehannaford.servicebus.windows.net/TrafficTopic/messages?api-version=2013-07 returned a response status of 400 Bad Request
Response Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>

    at com.microsoft.windowsazure.services.servicebus.implementation.ServiceBusExceptionProcessor.sendTopicMessage(ServiceBusExceptionProcessor.java:151)
    at uk.ac.ncl.yourname.csc8110.SendMessage.main(SendMessage.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.sun.jersey.api.client.UniformInterfaceException: POST https://nehannaford.servicebus.windows.net/TrafficTopic/messages?api-version=2013-07 returned a response status of 400 Bad Request
    at com.sun.jersey.api.client.WebResource.voidHandle(WebResource.java:707)
    at com.sun.jersey.api.client.WebResource.access$400(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:553)
    at com.microsoft.windowsazure.services.servicebus.implementation.ServiceBusRestProxy.sendMessage(ServiceBusRestProxy.java:194)
    at com.microsoft.windowsazure.services.servicebus.implementation.ServiceBusRestProxy.sendTopicMessage(ServiceBusRestProxy.java:305)
    at com.microsoft.windowsazure.services.servicebus.implementation.ServiceBusExceptionProcessor.sendTopicMessage(ServiceBusExceptionProcessor.java:149)
    ... 6 more
----
