= Online Resources

This page will be updated regularly by CSC8110 demonstrators to provide additional online resources we think you may find useful.

If there is something you would like to appear on this page, don't hesitate to contact Matthew Forshaw (mailto:matthew.forshaw@ncl.ac.uk[matthew.forshaw@ncl.ac.uk]) and he will update the page accordingly.

'''

link:https://azure.microsoft.com/en-gb/documentation/articles/virtual-machines-command-line-tools/[Using the Azure CLI for Mac, Linux, and Windows with Azure Service Management]

'''

== Maven and Version Control

=== Installing Git and Maven under Windows

==== Video 1: link:https://www.youtube.com/watch?v=7RkLdstgVA0[CSC8110: Installing Git and Maven in Windows]
This video shows you the process of downloading Git and Maven, and installing these on your system. This is a Windows specific guide, so if you are using another operating system (e.g. Linux or Mac OS X), please let me know and I will be able to provide you with custom instructions for these platforms. I have been assured that Git is installed on your University machines, so this step should not be necessary if you are not using your own machine.

==== Video 2: link:https://www.youtube.com/watch?v=oLzr3XphpIE[CSC8110: Creating your first Maven project.]
This video accompanies the link:https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html["Maven in 5 minutes"] guide; and guides you through the process of creating a Maven project for Java, and shows you how to execute your project from the command line.

'''
If you would like to use Maven or Version Control in your coursework, but haven't had much experience of this in the past, the following links provide step-by-step guides to performing their basic operations:
    
=== Version Control

link:https://git-scm.com/book/en/v2[Pro Git v2] (Great introductory book, avilable online for free, by Scott Chacon and Ben Straub. Chapters 1 and 2 are useful for an introduction!)

link:https://try.github.io/levels/1/challenges/1[Learn Git in 15 minutes]
link:http://homepages.cs.ncl.ac.uk/matthew.forshaw/teaching/csc8622/versioncontrol/[Version Control with Git] (Longer Practical)

'''
=== Maven

link:http://books.sonatype.com/mvnex-book/reference/introduction.html[Introduction to Maven]

link:http://books.sonatype.com/mvnex-book/reference/simple-project-sect-create-simple.html[Creating a Simple Project in Maven]

NOTE: In the Maven tutorial, the first command typed spans four lines, with the '\' symbol denoting a new-line.
