= CSC8110 Cloud Computing Coursework

== Tutorials
There are a number of tutorials to guide you in your use of the various Microsoft Azure technologies you will use in this coursework.

link:https://azure.microsoft.com/en-gb/documentation/articles/virtual-machines-linux-tutorial-portal-rm/[Practical One: Creating a Virtual Machine using Linux]

link:https://azure.microsoft.com/en-gb/documentation/articles/service-bus-java-how-to-use-topics-subscriptions/[Practical Two: How to use Azure Service Bus topics and subscriptions]

link:https://azure.microsoft.com/en-gb/documentation/articles/storage-java-how-to-use-table-storage/[Practical Three: How to use Table storage from Java]
Note: a recent Azure SDK change has changed the way to create `CloudTable` objects. For detailed instructions of how to create `CloudTable` objects, please see the entry in the FAQ section link:https://github.com/NewcastleComputingScience/csc8110/blob/master/frequentlyaskedquestions.asciidoc#anchor-java-cloudtable[here].

== Coursework
The following document (and accompanying presentation slides) outline the requirements of the CSC8110 Cloud Computing assignment.

link:./coursework.asciidoc[View the coursework document]

link:./CSC8110CloudComputing_201617_CourseworkIntro.pdf[View the presentation slides]

== Online Resources

A number of online resources which you may find useful in completing this coursework, may be found at the following link.

link:./onlineresources.asciidoc[Online Resources]


== Frequently Asked Questions (FAQs)
A live document containing Frequently Asked Quesitons (FAQs) will be maintained at the following link. If you are encountering difficulties completing the coursework assignment, please check the following link to see if your issue has already been answered.

link:./frequentlyaskedquestions.asciidoc[View the Frequently Asked Questions document]
